export type Module = { id: string; number: string; title: string; short: string; level: "Base" | "Intermedio" | "Avanzado"; minutes: number };
export type Question = { id: number; moduleId: string; prompt: string; options: string[]; answer: number; explanation: string };

export const modules: Module[] = [
  { id: "fundamentos", number: "01", title: "Fundamentos del efecto polvo", short: "Propósito, mezcla óptica, estilos y criterio profesional.", level: "Base", minutes: 8 },
  { id: "arte", number: "02", title: "Principios artísticos", short: "Degradado, saturación, luz, sombra y definición.", level: "Base", minutes: 10 },
  { id: "puntillismo", number: "03", title: "Puntillismo de arrastre", short: "Distribución del pigmento, transiciones y movimientos.", level: "Intermedio", minutes: 12 },
  { id: "dominio", number: "04", title: "Dominio técnico", short: "Presión, velocidad de mano, ángulo y control del patrón.", level: "Intermedio", minutes: 12 },
  { id: "piel", number: "05", title: "Piel y profundidad", short: "Planos anatómicos, lectura del tejido y señales fisiológicas.", level: "Avanzado", minutes: 14 },
  { id: "cicatrizacion", number: "06", title: "Respuesta y cicatrización", short: "Tipos de piel, fases de reparación, retención y retoque.", level: "Avanzado", minutes: 14 },
  { id: "seguridad", number: "07", title: "Cuidados y seguridad", short: "Cuidados posteriores, complicaciones y contraindicaciones.", level: "Intermedio", minutes: 10 },
  { id: "equipos", number: "08", title: "Máquinas y agujas", short: "Stroke, voltaje, velocidad, calibres, agrupaciones y taper.", level: "Avanzado", minutes: 15 },
];

export const questions: Question[] = [
  { id: 1, moduleId: "fundamentos", prompt: "¿Qué construye visualmente una ceja efecto polvo?", options: ["Líneas que imitan pelos", "Miles de microdepósitos distribuidos estratégicamente", "Un bloque uniforme de pigmento", "Una incisión continua"], answer: 1, explanation: "La mezcla óptica hace que miles de puntos controlados se perciban como una nube suave de color." },
  { id: 2, moduleId: "fundamentos", prompt: "¿Cuál es el verdadero objetivo de la técnica?", options: ["Oscurecer al máximo", "Reemplazar el vello", "Mejorar la estructura mediante una distribución estratégica del color", "Crear bordes rígidos"], answer: 2, explanation: "La técnica busca densidad, equilibrio y definición respetando la anatomía facial y la naturalidad." },
  { id: 3, moduleId: "fundamentos", prompt: "¿Qué diferencia principalmente al efecto makeup?", options: ["Ausencia de degradado", "Mayor saturación con un degradado elegante", "Uso exclusivo de tres puntas", "Trabajo únicamente superficial"], answer: 1, explanation: "El efecto makeup eleva la definición del cuerpo y la cola, pero conserva un inicio suave y transiciones controladas." },
  { id: 4, moduleId: "arte", prompt: "En esta técnica, ¿qué significa saturación?", options: ["La oscuridad del pigmento en el frasco", "La cantidad de información visual o concentración de pigmento en una zona", "La temperatura del color", "La velocidad de cicatrización"], answer: 1, explanation: "La saturación organiza la intensidad visual: más concentración produce mayor peso; menos, mayor ligereza." },
  { id: 5, moduleId: "arte", prompt: "¿Cómo se crea visualmente una zona de luz?", options: ["Aumentando la presión", "Usando pigmento blanco", "Dejando menor saturación", "Dibujando un borde"], answer: 2, explanation: "Las zonas menos saturadas parecen captar más luz y producen transiciones más naturales." },
  { id: 6, moduleId: "arte", prompt: "Una buena definición debe…", options: ["endurecer todos los límites", "eliminar el degradado", "conservar estructura sin crear un borde dibujado", "concentrarse solo en el inicio"], answer: 2, explanation: "Definición y degradado se complementan; una forma clara no necesita contornos rígidos." },
  { id: 7, moduleId: "puntillismo", prompt: "¿Qué controla principalmente la distancia entre puntos?", options: ["La percepción de saturación", "El subtono de la piel", "La longitud de la ceja", "La fase inflamatoria"], answer: 0, explanation: "Puntos más próximos generan mayor densidad visual; una separación mayor construye zonas suaves y luminosas." },
  { id: 8, moduleId: "puntillismo", prompt: "¿Para qué sirve una transición?", options: ["Para compactar una sola zona", "Para pasar gradualmente entre niveles de intensidad", "Para medir la aguja", "Para elegir el pigmento"], answer: 1, explanation: "La transición evita saltos, parches y cambios bruscos entre zonas de saturación." },
  { id: 9, moduleId: "puntillismo", prompt: "En una distribución clásica, el inicio de la ceja suele recibir…", options: ["la máxima saturación", "una saturación baja", "un borde compacto", "la mayor presión"], answer: 1, explanation: "El inicio suave reduce el peso visual y permite integrar la ceja naturalmente con el rostro." },
  { id: 10, moduleId: "dominio", prompt: "Si los impactos quedan demasiado juntos sin control, el resultado puede…", options: ["compactarse y perder el degradado", "volverse más natural", "cicatrizar más rápido", "reducir el trauma"], answer: 0, explanation: "La acumulación excesiva concentra el pigmento, aumenta el trauma y destruye las transiciones." },
  { id: 11, moduleId: "dominio", prompt: "¿Qué debe guiar un ajuste técnico durante el procedimiento?", options: ["Una cifra universal", "La respuesta observable de la piel", "La preferencia del fabricante", "La cantidad de maquillaje de la profesional"], answer: 1, explanation: "El tejido cambia entre personas y zonas; el criterio nace de observar resistencia, eritema, exudado y retención." },
  { id: 12, moduleId: "dominio", prompt: "¿Cuál es un error frecuente al buscar más intensidad?", options: ["Construirla progresivamente", "Aumentar indiscriminadamente presión y pasadas", "Separar los puntos", "Reducir el contraste"], answer: 1, explanation: "La intensidad debe construirse con control; más fuerza o recorridos no equivalen a mejor implantación." },
  { id: 13, moduleId: "piel", prompt: "¿Dónde se busca una implantación controlada para PMU?", options: ["En la hipodermis", "En un plano superficial próximo a la transición epidérmica y dermis papilar", "En la dermis reticular profunda", "Únicamente sobre el estrato córneo"], answer: 1, explanation: "El objetivo es un plano superficial y controlado; demasiado superficial se pierde y demasiado profundo aumenta riesgos." },
  { id: 14, moduleId: "piel", prompt: "¿La salida visible de la aguja equivale a la profundidad real?", options: ["Sí, siempre", "Solo con 1RL", "No; es un margen operativo", "Solo en piel grasa"], answer: 2, explanation: "Solo una pequeña fracción de la aguja expuesta entra en el tejido; la mano y la respuesta de la piel determinan la profundidad." },
  { id: 15, moduleId: "piel", prompt: "¿Qué puede indicar una implantación excesivamente profunda?", options: ["Trauma mayor, sangrado y riesgo de migración", "Ausencia total de respuesta", "Mayor naturalidad", "Retención siempre perfecta"], answer: 0, explanation: "Profundizar de más eleva el daño tisular y puede causar color frío, migración, fibrosis o cicatriz." },
  { id: 16, moduleId: "cicatrizacion", prompt: "¿Por qué la ceja suele perder intensidad al cicatrizar?", options: ["Porque todo el pigmento desaparece", "Por descamación, inflamación y reorganización óptica del tejido", "Por el voltaje", "Porque la aguja cambia de calibre"], answer: 1, explanation: "El aspecto inmediato no es el resultado final; la piel se repara y modifica temporalmente la percepción del pigmento." },
  { id: 17, moduleId: "cicatrizacion", prompt: "¿Cuál es la función principal del retoque?", options: ["Transformar por completo el diseño", "Optimizar zonas de menor retención y equilibrar el resultado", "Oscurecer obligatoriamente", "Repetir todo con mayor presión"], answer: 1, explanation: "El retoque permite evaluar el resultado cicatrizado y hacer ajustes selectivos, no rehacer automáticamente el procedimiento." },
  { id: 18, moduleId: "cicatrizacion", prompt: "Una piel delgada exige especialmente…", options: ["más fuerza", "movimientos lentos y repetidos", "mano ligera y construcción progresiva", "aguja de mayor calibre"], answer: 2, explanation: "La piel fina puede aceptar pigmento con facilidad y traumatizarse antes; necesita observación y control conservador." },
  { id: 19, moduleId: "seguridad", prompt: "¿Qué debe hacerse ante una respuesta inusual o desproporcionada?", options: ["Aumentar el voltaje", "Ocultarla con más pigmento", "Suspender, evaluar y actuar según el protocolo", "Continuar hasta terminar"], answer: 2, explanation: "La seguridad prevalece sobre completar el diseño. Una respuesta anormal requiere detenerse y reevaluar." },
  { id: 20, moduleId: "seguridad", prompt: "Durante la cicatrización, las costras deben…", options: ["retirarse para liberar pigmento", "dejarse desprender naturalmente", "cubrirse con maquillaje", "frotarse diariamente"], answer: 1, explanation: "Arrancarlas puede retirar pigmento, reabrir la microlesión y aumentar el riesgo de infección o cicatriz." },
  { id: 21, moduleId: "seguridad", prompt: "¿Cuál es la base de unos buenos cuidados posteriores?", options: ["Mantener higiene y seguir indicaciones sin manipular", "Aplicar cualquier cosmético", "Exponer al sol", "Saturar de productos"], answer: 0, explanation: "La higiene, la protección y el cumplimiento de instrucciones favorecen una reparación estable." },
  { id: 22, moduleId: "equipos", prompt: "¿Qué describe el stroke?", options: ["La profundidad exacta en piel", "El recorrido mecánico del sistema impulsor", "La salida visible", "El diámetro de la punta"], answer: 1, explanation: "Stroke, salida y profundidad se relacionan, pero no son equivalentes. El stroke describe la amplitud mecánica del ciclo." },
  { id: 23, moduleId: "equipos", prompt: "¿Cuál es la diferencia correcta entre RL y RS?", options: ["RL es compacto y preciso; RS distribuye sobre una superficie más abierta", "RS tiene siempre una sola punta", "RL solo sirve para tatuaje corporal", "No existe diferencia"], answer: 0, explanation: "Round Liner agrupa las puntas de manera compacta; Round Shader las separa para ampliar la huella." },
  { id: 24, moduleId: "equipos", prompt: "¿Qué taper ofrece un equilibrio habitual entre control e implantación?", options: ["Short", "Medium", "Extra Long", "Ninguno"], answer: 1, explanation: "El taper medio se presenta como una opción equilibrada y adecuada para muchos procedimientos y niveles de experiencia." },
];

export const cases = [
  { title: "Inicio demasiado compacto", situation: "El inicio se ve tan intenso como la cola y la ceja pierde ligereza.", diagnosis: "Falta de gradiente y exceso de saturación en la zona de luz.", action: "Reducir la densidad de impactos en el inicio y construir una transición progresiva hacia cuerpo y cola." },
  { title: "Piel fina con eritema temprano", situation: "La piel acepta color con facilidad, pero enrojece antes de completar varias pasadas.", diagnosis: "Tejido delicado con riesgo de sobretrabajo.", action: "Mantener una mano ligera, reducir repeticiones y evaluar la respuesta antes de buscar más intensidad." },
  { title: "Color irregular al cicatrizar", situation: "El resultado presenta zonas más densas y otras con baja retención.", diagnosis: "Distribución inconsistente, posiblemente asociada a cambios de velocidad, presión o distancia.", action: "Evaluar el patrón completo en el retoque y corregir solo las zonas necesarias con parámetros estables." },
  { title: "Confusión entre stroke y profundidad", situation: "Una profesional cree que un stroke de 3 mm significa penetrar 3 mm en piel.", diagnosis: "Interpretación incorrecta del parámetro mecánico.", action: "Recordar que el stroke es el recorrido del sistema; la profundidad real depende del control manual y del tejido." },
];
