export type Module = { id: string; number: string; title: string; short: string; level: "Base" | "Intermedio" | "Avanzado"; minutes: number };
export type Question = { id: number; moduleId: string; prompt: string; options: string[]; answer: number; explanation: string };

export const modules: Module[] = [
  { id: "fundamentos", number: "01", title: "Fundamentos del efecto polvo", short: "Propósito, mezcla óptica, estilos y criterio profesional.", level: "Base", minutes: 8 },
  { id: "arte", number: "02", title: "Principios artísticos", short: "Degradado, saturación, luz, sombra y definición.", level: "Base", minutes: 10 },
  { id: "puntillismo", number: "03", title: "Puntillismo de arrastre", short: "Distribución del pigmento, transiciones y movimientos.", level: "Intermedio", minutes: 12 },
  { id: "dominio", number: "04", title: "Dominio técnico", short: "Presión, velocidad de mano, ángulo y control del patrón.", level: "Intermedio", minutes: 12 },
  { id: "piel", number: "05", title: "Piel y profundidad", short: "Planos anatómicos, lectura del tejido y señales fisiológicas.", level: "Avanzado", minutes: 14 },
  { id: "cicatrizacion", number: "06", title: "Respuesta y cicatrización", short: "Tipos de piel, fases de reparación, retención y retoque.", level: "Avanzado", minutes: 14 },
  { id: "seguridad", number: "07", title: "Cuidados y seguridad", short: "Cuidados posteriores, complicaciones y contraindicaciones.", level: "Intermedio", minutes: 10 },
  { id: "equipos", number: "08", title: "Máquinas y agujas", short: "Stroke, voltaje, velocidad, calibres, agrupaciones y taper.", level: "Avanzado", minutes: 15 },
];

export const questions: Question[] = [
  { id: 1, moduleId: "fundamentos", prompt: "¿Qué construye visualmente una ceja efecto polvo?", options: ["Líneas que imitan pelos", "Miles de microdepósitos distribuidos estratégicamente", "Un bloque uniforme de pigmento", "Una incisión continua"], answer: 1, explanation: "La mezcla óptica hace que miles de puntos controlados se perciban como una nube suave de color." },
  { id: 2, moduleId: "fundamentos", prompt: "¿Cuál es el verdadero objetivo de la técnica?", options: ["Oscurecer al máximo", "Reemplazar el vello", "Mejorar la estructura mediante una distribución estratégica del color", "Crear bordes rígidos"], answer: 2, explanation: "La técnica busca densidad, equilibrio y definición respetando la anatomía facial y la naturalidad." },
  { id: 3, moduleId: "fundamentos", prompt: "¿Qué diferencia principalmente al efecto makeup?", options: ["Ausencia de degradado", "Mayor saturación con un degradado elegante", "Uso exclusivo de tres puntas", "Trabajo únicamente superficial"], answer: 1, explanation: "El efecto makeup eleva la definición del cuerpo y la cola, pero conserva un inicio suave y transiciones controladas." },
  { id: 4, moduleId: "arte", prompt: "En esta técnica, ¿qué significa saturación?", options: ["La oscuridad del pigmento en el frasco", "La cantidad de información visual o concentración de pigmento en una zona", "La temperatura del color", "La velocidad de cicatrización"], answer: 1, explanation: "La saturación organiza la intensidad visual: más concentración produce mayor peso; menos, mayor ligereza." },
  { id: 5, moduleId: "arte", prompt: "¿Cómo se crea visualmente una zona de luz?", options: ["Aumentando la presión", "Usando pigmento blanco", "Dejando menor saturación", "Dibujando un borde"], answer: 2, explanation: "Las zonas menos saturadas parecen captar más luz y producen transiciones más naturales." },
  { id: 6, moduleId: "arte", prompt: "Una buena definición debe…", options: ["endurecer todos los límites", "eliminar el degradado", "conservar estructura sin crear un borde dibujado", "concentrarse solo en el inicio"], answer: 2, explanation: "Definición y degradado se complementan; una forma clara no necesita contornos rígidos." },
  { id: 7, moduleId: "puntillismo", prompt: "¿Qué controla principalmente la distancia entre puntos?", options: ["La percepción de saturación", "El subtono de la piel", "La longitud de la ceja", "La fase inflamatoria"], answer: 0, explanation: "Puntos más próximos generan mayor densidad visual; una separación mayor construye zonas suaves y luminosas." },
  { id: 8, moduleId: "puntillismo", prompt: "¿Para qué sirve una transición?", options: ["Para compactar una sola zona", "Para pasar gradualmente entre niveles de intensidad", "Para medir la aguja", "Para elegir el pigmento"], answer: 1, explanation: "La transición evita saltos, parches y cambios bruscos entre zonas de saturación." },
  { id: 9, moduleId: "puntillismo", prompt: "En una distribución clásica, el inicio de la ceja suele recibir…", options: ["la máxima saturación", "una saturación baja", "un borde compacto", "la mayor presión"], answer: 1, explanation: "El inicio suave reduce el peso visual y permite integrar la ceja naturalmente con el rostro." },
  { id: 10, moduleId: "dominio", prompt: "Si los impactos quedan demasiado juntos sin control, el resultado puede…", options: ["compactarse y perder el degradado", "volverse más natural", "cicatrizar más rápido", "reducir el trauma"], answer: 0, explanation: "La acumulación excesiva concentra el pigmento, aumenta el trauma y destruye las transiciones." },
  { id: 11, moduleId: "dominio", prompt: "¿Qué debe guiar un ajuste técnico durante el procedimiento?", options: ["Una cifra universal", "La respuesta observable de la piel", "La preferencia del fabricante", "La cantidad de maquillaje de la profesional"], answer: 1, explanation: "El tejido cambia entre personas y zonas; el criterio nace de observar resistencia, eritema, exudado y retención." },
  { id: 12, moduleId: "dominio", prompt: "¿Cuál es un error frecuente al buscar más intensidad?", options: ["Construirla progresivamente", "Aumentar indiscriminadamente presión y pasadas", "Separar los puntos", "Reducir el contraste"], answer: 1, explanation: "La intensidad debe construirse con control; más fuerza o recorridos no equivalen a mejor implantación." },
  { id: 13, moduleId: "piel", prompt: "¿Dónde se busca una implantación controlada para PMU?", options: ["En la hipodermis", "En un plano superficial próximo a la transición epidérmica y dermis papilar", "En la dermis reticular profunda", "Únicamente sobre el estrato córneo"], answer: 1, explanation: "El objetivo es un plano superficial y controlado; demasiado superficial se pierde y demasiado profundo aumenta riesgos." },
  { id: 14, moduleId: "piel", prompt: "¿La salida visible de la aguja equivale a la profundidad real?", options: ["Sí, siempre", "Solo con 1RL", "No; es un margen operativo", "Solo en piel grasa"], answer: 2, explanation: "Solo una pequeña fracción de la aguja expuesta entra en el tejido; la mano y la respuesta de la piel determinan la profundidad." },
  { id: 15, moduleId: "piel", prompt: "¿Qué puede indicar una implantación excesivamente profunda?", options: ["Trauma mayor, sangrado y riesgo de migración", "Ausencia total de respuesta", "Mayor naturalidad", "Retención siempre perfecta"], answer: 0, explanation: "Profundizar de más eleva el daño tisular y puede causar color frío, migración, fibrosis o cicatriz." },
  { id: 16, moduleId: "cicatrizacion", prompt: "¿Por qué la ceja suele perder intensidad al cicatrizar?", options: ["Porque todo el pigmento desaparece", "Por descamación, inflamación y reorganización óptica del tejido", "Por el voltaje", "Porque la aguja cambia de calibre"], answer: 1, explanation: "El aspecto inmediato no es el resultado final; la piel se repara y modifica temporalmente la percepción del pigmento." },
  { id: 17, moduleId: "cicatrizacion", prompt: "¿Cuál es la función principal del retoque?", options: ["Transformar por completo el diseño", "Optimizar zonas de menor retención y equilibrar el resultado", "Oscurecer obligatoriamente", "Repetir todo con mayor presión"], answer: 1, explanation: "El retoque permite evaluar el resultado cicatrizado y hacer ajustes selectivos, no rehacer automáticamente el procedimiento." },
  { id: 18, moduleId: "cicatrizacion", prompt: "Una piel delgada exige especialmente…", options: ["más fuerza", "movimientos lentos y repetidos", "mano ligera y construcción progresiva", "aguja de mayor calibre"], answer: 2, explanation: "La piel fina puede aceptar pigmento con facilidad y traumatizarse antes; necesita observación y control conservador." },
  { id: 19, moduleId: "seguridad", prompt: "¿Qué debe hacerse ante una respuesta inusual o desproporcionada?", options: ["Aumentar el voltaje", "Ocultarla con más pigmento", "Suspender, evaluar y actuar según el protocolo", "Continuar hasta terminar"], answer: 2, explanation: "La seguridad prevalece sobre completar el diseño. Una respuesta anormal requiere detenerse y reevaluar." },
  { id: 20, moduleId: "seguridad", prompt: "Durante la cicatrización, las costras deben…", options: ["retirarse para liberar pigmento", "dejarse desprender naturalmente", "cubrirse con maquillaje", "frotarse diariamente"], answer: 1, explanation: "Arrancarlas puede retirar pigmento, reabrir la microlesión y aumentar el riesgo de infección o cicatriz." },
  { id: 21, moduleId: "seguridad", prompt: "¿Cuál es la base de unos buenos cuidados posteriores?", options: ["Mantener higiene y seguir indicaciones sin manipular", "Aplicar cualquier cosmético", "Exponer al sol", "Saturar de productos"], answer: 0, explanation: "La higiene, la protección y el cumplimiento de instrucciones favorecen una reparación estable." },
  { id: 22, moduleId: "equipos", prompt: "¿Qué describe el stroke?", options: ["La profundidad exacta en piel", "El recorrido mecánico del sistema impulsor", "La salida visible", "El diámetro de la punta"], answer: 1, explanation: "Stroke, salida y profundidad se relacionan, pero no son equivalentes. El stroke describe la amplitud mecánica del ciclo." },
  { id: 23, moduleId: "equipos", prompt: "¿Cuál es la diferencia correcta entre RL y RS?", options: ["RL es compacto y preciso; RS distribuye sobre una superficie más abierta", "RS tiene siempre una sola punta", "RL solo sirve para tatuaje corporal", "No existe diferencia"], answer: 0, explanation: "Round Liner agrupa las puntas de manera compacta; Round Shader las separa para ampliar la huella." },
  { id: 24, moduleId: "equipos", prompt: "¿Qué taper ofrece un equilibrio habitual entre control e implantación?", options: ["Short", "Medium", "Extra Long", "Ninguno"], answer: 1, explanation: "El taper medio se presenta como una opción equilibrada y adecuada para muchos procedimientos y niveles de experiencia." },
  { id: 25, moduleId: "fundamentos", prompt: "¿Por qué la técnica recibe nombres comerciales diferentes?", options: ["Porque cada nombre usa una capa distinta de piel", "Porque suelen describir variaciones estéticas de un mismo principio biomecánico", "Porque cada nombre exige una máquina exclusiva", "Porque cambia la composición de la epidermis"], answer: 1, explanation: "Muchos nombres describen estilos o metodologías comerciales, pero comparten la implantación estratégica de microdepósitos para crear un degradado." },
  { id: 26, moduleId: "fundamentos", prompt: "¿Qué principio permite percibir muchos puntos como una superficie continua?", options: ["Contraste simultáneo", "Mezcla óptica", "Metamerismo", "Reflexión especular"], answer: 1, explanation: "El cerebro integra los puntos microscópicos y los interpreta como una nube continua de color." },
  { id: 27, moduleId: "fundamentos", prompt: "¿Cuál es una ventaja de la técnica efecto polvo?", options: ["Produce siempre el mismo acabado", "Permite adaptar la intensidad al estilo de cada cliente", "Elimina la necesidad de diagnosticar la piel", "Garantiza retención idéntica en todas las personas"], answer: 1, explanation: "La distribución de saturación, el degradado y los parámetros técnicos permiten personalizar desde un acabado suave hasta uno más definido." },
  { id: 28, moduleId: "fundamentos", prompt: "¿Qué caracteriza al efecto luz y sombra?", options: ["Un relleno completamente uniforme", "La manipulación de intensidad para crear sensación de volumen", "La ausencia de zonas suaves", "El uso obligatorio de pigmento negro"], answer: 1, explanation: "Las áreas más saturadas aportan profundidad y las más suaves simulan luz, creando una lectura tridimensional." },
  { id: 29, moduleId: "fundamentos", prompt: "¿Qué debe prevalecer al elegir el estilo final?", options: ["La tendencia más popular", "La anatomía, preferencias y características de la cliente", "La máxima intensidad posible", "El nombre comercial de la técnica"], answer: 1, explanation: "El resultado debe responder al rostro, el tejido, el maquillaje habitual y las expectativas reales de cada persona." },

  { id: 30, moduleId: "arte", prompt: "¿Qué es un degradado?", options: ["Una línea que separa dos tonos", "Una transición progresiva entre niveles de intensidad", "Una mezcla de dos pigmentos en el godete", "Una zona sin diseño"], answer: 1, explanation: "El degradado permite que el color cambie de forma gradual sin interrupciones ni saltos visuales." },
  { id: 31, moduleId: "arte", prompt: "¿Qué aporta la sombra dentro de la composición?", options: ["Ligereza", "Profundidad y estructura", "Transparencia", "Una temperatura más cálida"], answer: 1, explanation: "Las zonas de mayor saturación poseen más peso visual y ayudan al cerebro a interpretar volumen y estructura." },
  { id: 32, moduleId: "arte", prompt: "¿Qué ocurre si definición y degradado compiten entre sí?", options: ["El diseño puede percibirse rígido y artificial", "La cicatrización se acelera", "El pigmento se vuelve orgánico", "La piel aumenta su espesor"], answer: 0, explanation: "Una definición excesiva puede endurecer los límites y destruir las transiciones suaves que caracterizan un buen efecto polvo." },
  { id: 33, moduleId: "arte", prompt: "¿Dónde suele concentrarse mayor peso visual en una ceja equilibrada?", options: ["En el inicio", "En cuerpo y cola de manera controlada", "En todo el contorno", "Fuera del diseño"], answer: 1, explanation: "El cuerpo y la cola suelen admitir más definición, mientras el inicio conserva ligereza para integrarse con el rostro." },
  { id: 34, moduleId: "arte", prompt: "¿Qué elemento dirige primero la mirada del observador?", options: ["Las zonas de mayor contraste e intensidad", "Las zonas completamente vacías", "La marca de la máquina", "El número de pasadas"], answer: 0, explanation: "El contraste y la saturación organizan la jerarquía visual y determinan dónde se concentra la atención." },

  { id: 35, moduleId: "puntillismo", prompt: "¿Qué sucede cuando aumenta gradualmente la proximidad entre impactos?", options: ["Disminuye la saturación", "Aumenta la percepción de densidad", "Desaparece el pigmento", "Cambia el fototipo"], answer: 1, explanation: "La cercanía controlada entre puntos incrementa la información visual y construye zonas más saturadas." },
  { id: 36, moduleId: "puntillismo", prompt: "¿Cuál es la finalidad de dividir la ceja en zonas?", options: ["Aplicar la misma densidad en todas", "Planificar la distribución progresiva de la saturación", "Medir la profundidad en milímetros", "Elegir el cartucho"], answer: 1, explanation: "La zonificación ayuda a decidir dónde conservar luz, dónde crear transición y dónde aportar mayor definición." },
  { id: 37, moduleId: "puntillismo", prompt: "¿Qué diferencia básica existe entre un movimiento unidireccional y uno bidireccional?", options: ["El sentido y la forma en que se distribuyen los impactos", "El color del pigmento", "El número de agujas del cartucho", "La fase de cicatrización"], answer: 0, explanation: "La dirección del recorrido modifica el patrón de impactos y debe elegirse según la zona y el efecto que se desea construir." },
  { id: 38, moduleId: "puntillismo", prompt: "¿Qué indica una transición con parches visibles?", options: ["Una distribución irregular de impactos", "Una selección correcta del fototipo", "Un degradado bien construido", "Una salida de aguja perfecta"], answer: 0, explanation: "Los parches revelan cambios bruscos en distancia, velocidad, presión o número de recorridos." },
  { id: 39, moduleId: "puntillismo", prompt: "¿Por qué conviene practicar patrones sobre látex o papel?", options: ["Para sustituir el conocimiento de la piel", "Para desarrollar constancia de movimiento y lectura visual antes de trabajar tejido", "Para determinar contraindicaciones", "Para evitar aprender degradados"], answer: 1, explanation: "La práctica controlada ayuda a entrenar ritmo, distancia y dirección sin comprometer tejido vivo." },

  { id: 40, moduleId: "dominio", prompt: "¿Qué relación debe existir entre velocidad de mano y velocidad de máquina?", options: ["Deben analizarse en conjunto", "Siempre deben ser máximas", "No se relacionan", "Una reemplaza a la otra"], answer: 0, explanation: "La frecuencia de impactos y el desplazamiento de la mano determinan juntos cuántos depósitos quedan en cada zona." },
  { id: 41, moduleId: "dominio", prompt: "Si la mano avanza demasiado lentamente sobre una misma zona, puede producirse…", options: ["Acumulación de impactos y sobretrabajo", "Menor contacto siempre", "Un fototipo diferente", "Ausencia de pigmento"], answer: 0, explanation: "Una permanencia excesiva aumenta la densidad y el trauma, incluso cuando la presión parece ligera." },
  { id: 42, moduleId: "dominio", prompt: "¿Por qué no existe un parámetro universal para todas las profesionales?", options: ["Porque las máquinas, agujas, manos y pieles responden de forma diferente", "Porque el voltaje no existe", "Porque toda piel es idéntica", "Porque solo importa el pigmento"], answer: 0, explanation: "Los números deben interpretarse dentro de un sistema: equipo, cartucho, técnica, velocidad manual y respuesta del tejido." },
  { id: 43, moduleId: "dominio", prompt: "¿Qué debe hacerse antes de repetir recorridos para intensificar?", options: ["Observar la respuesta y la distribución ya conseguida", "Aumentar siempre la presión", "Cambiar obligatoriamente de pigmento", "Ignorar el eritema"], answer: 0, explanation: "Evaluar el tejido y el patrón evita añadir impactos innecesarios y permite corregir solo donde hace falta." },
  { id: 44, moduleId: "dominio", prompt: "¿Qué demuestra verdadero dominio técnico?", options: ["Trabajar siempre rápido", "Adaptar los parámetros conservando un resultado predecible y respetuoso", "Usar el stroke más largo", "Completar muchas pasadas"], answer: 1, explanation: "El dominio consiste en ajustar conscientemente la técnica al tejido y al objetivo, no en repetir una receta fija." },

  { id: 45, moduleId: "piel", prompt: "¿Por qué la epidermis no es un depósito estable por sí sola?", options: ["Porque está vascularizada", "Porque se renueva continuamente", "Porque contiene tejido adiposo", "Porque no recibe luz"], answer: 1, explanation: "La renovación epidérmica favorece la eliminación de pigmento situado demasiado superficialmente." },
  { id: 46, moduleId: "piel", prompt: "¿Qué característica distingue a la dermis?", options: ["Es una capa queratinizada sin vasos", "Es un tejido vascularizado e inervado", "Está formada principalmente por grasa", "Se desprende cada semana"], answer: 1, explanation: "La dermis contiene vasos, terminaciones nerviosas y fibras de soporte; trabajar demasiado profundo aumenta el trauma." },
  { id: 47, moduleId: "piel", prompt: "¿Qué es la hipodermis?", options: ["La capa más superficial", "El tejido situado bajo la dermis, compuesto principalmente por grasa", "Una parte del cartucho", "El pigmento cicatrizado"], answer: 1, explanation: "La hipodermis se ubica debajo de la dermis y no corresponde al plano de trabajo de la micropigmentación." },
  { id: 48, moduleId: "piel", prompt: "¿Qué respuesta puede considerarse orientativa durante una implantación controlada?", options: ["La observación conjunta de eritema, exudado y resistencia", "Solo el número del voltaje", "La longitud total de la aguja", "El color del cartucho"], answer: 0, explanation: "La profundidad no se adivina por una cifra aislada; se interpreta a partir de varias señales del tejido." },
  { id: 49, moduleId: "piel", prompt: "¿Qué puede ocurrir si el pigmento queda demasiado superficial?", options: ["Puede perderse con mayor facilidad durante la renovación", "Siempre se vuelve azul", "Genera fibrosis automáticamente", "Permanece intacto por años"], answer: 0, explanation: "Una implantación excesivamente superficial suele producir baja retención o desaparición irregular tras la cicatrización." },

  { id: 50, moduleId: "cicatrizacion", prompt: "¿Qué inicia inmediatamente después de la microlesión?", options: ["Los mecanismos de defensa y reparación", "La remodelación final", "La eliminación completa del pigmento", "La formación de tejido adiposo"], answer: 0, explanation: "La coagulación y la respuesta inflamatoria comienzan desde los primeros momentos para estabilizar y reparar el tejido." },
  { id: 51, moduleId: "cicatrizacion", prompt: "¿Qué ocurre principalmente en la fase proliferativa?", options: ["Se reconstruye tejido y se produce nuevo colágeno", "Se elige el pigmento", "Se regula el stroke", "Se realiza el diseño inicial"], answer: 0, explanation: "Los fibroblastos y otras células participan en la reparación y reconstrucción de la zona tratada." },
  { id: 52, moduleId: "cicatrizacion", prompt: "¿Qué caracteriza la fase de remodelación?", options: ["La reorganización progresiva del colágeno", "El sangrado inicial", "La implantación del pigmento", "La selección de aguja"], answer: 0, explanation: "En la fase final, las fibras se reorganizan y el tejido adquiere gradualmente mayor estabilidad." },
  { id: 53, moduleId: "cicatrizacion", prompt: "¿Por qué dos procedimientos visualmente similares pueden cicatrizar distinto?", options: ["Porque la respuesta biológica varía entre personas", "Porque el diseño no influye", "Porque toda piel retiene igual", "Porque el resultado inmediato es definitivo"], answer: 0, explanation: "Tipo de piel, respuesta inflamatoria, técnica, cuidados y otros factores modifican la evolución del pigmento." },
  { id: 54, moduleId: "cicatrizacion", prompt: "¿Cuándo debe valorarse realmente la necesidad de un retoque?", options: ["Durante la primera inflamación", "Después de que el tejido complete el periodo de cicatrización indicado", "Inmediatamente al terminar", "Antes del procedimiento inicial"], answer: 1, explanation: "Solo el resultado cicatrizado permite distinguir baja retención, irregularidades reales y zonas que necesitan ajuste." },

  { id: 55, moduleId: "seguridad", prompt: "¿Qué práctica aumenta el riesgo durante la cicatrización?", options: ["Seguir el protocolo de higiene", "Manipular o arrancar descamaciones", "Evitar cosméticos no indicados", "Mantener las manos limpias"], answer: 1, explanation: "Manipular costras o descamaciones puede reabrir el tejido, retirar pigmento y favorecer complicaciones." },
  { id: 56, moduleId: "seguridad", prompt: "¿Qué diferencia una respuesta esperada de una complicación?", options: ["La intensidad, duración y evolución de los signos", "El precio del procedimiento", "La marca del pigmento solamente", "La hora del día"], answer: 0, explanation: "Eritema o sensibilidad leves pueden ser esperados; signos intensos, progresivos o persistentes requieren evaluación." },
  { id: 57, moduleId: "seguridad", prompt: "¿Qué función cumple la valoración previa?", options: ["Detectar riesgos, contraindicaciones y expectativas", "Garantizar un color idéntico", "Eliminar la necesidad de consentimiento", "Sustituir los cuidados posteriores"], answer: 0, explanation: "Una evaluación responsable permite decidir si proceder, adaptar o posponer el tratamiento." },
  { id: 58, moduleId: "seguridad", prompt: "Ante una contraindicación temporal, lo correcto es…", options: ["Trabajar con más velocidad", "Posponer hasta que la condición se resuelva o sea autorizada", "Ocultarla en la ficha", "Reducir solo el diseño"], answer: 1, explanation: "La seguridad exige aplazar cuando existe una condición temporal que aumenta el riesgo del procedimiento." },
  { id: 59, moduleId: "seguridad", prompt: "¿Por qué deben explicarse los cambios normales de cicatrización?", options: ["Para que la cliente no confunda la evolución esperada con un problema", "Para evitar entregar cuidados", "Para prometer retención total", "Para eliminar el retoque"], answer: 0, explanation: "Una expectativa informada mejora el cumplimiento de cuidados y permite identificar oportunamente signos anormales." },

  { id: 60, moduleId: "equipos", prompt: "¿Qué es la salida de aguja?", options: ["La porción visible que sobresale del cartucho", "La profundidad exacta en la dermis", "La longitud del stroke", "La velocidad del motor"], answer: 0, explanation: "La salida brinda visibilidad y margen operativo, pero no indica cuánto tejido penetra realmente la punta." },
  { id: 61, moduleId: "equipos", prompt: "¿Qué expresa el voltaje?", options: ["La energía suministrada al motor", "El diámetro de la aguja", "La profundidad en milímetros", "La cantidad de pigmento cicatrizado"], answer: 0, explanation: "El voltaje influye en el funcionamiento del motor, aunque la velocidad real también depende del diseño y la carga del sistema." },
  { id: 62, moduleId: "equipos", prompt: "¿Por qué dos máquinas al mismo voltaje pueden comportarse distinto?", options: ["Por diferencias de motor, electrónica, transmisión y cartucho", "Porque el voltaje cambia el fototipo", "Porque una no tiene aguja", "Porque la piel deja de influir"], answer: 0, explanation: "El número mostrado no describe por sí solo la respuesta mecánica completa de cada equipo." },
  { id: 63, moduleId: "equipos", prompt: "¿Qué configuraciones se utilizan con frecuencia para efecto polvo?", options: ["1RL y 3RL", "Solo magnum de 15 puntas", "Únicamente flat", "Ninguna aguja redonda"], answer: 0, explanation: "Las configuraciones 1RL y 3RL ofrecen precisión y permiten controlar la distribución del pigmento." },
  { id: 64, moduleId: "equipos", prompt: "¿Qué debe revisarse además del número de puntas?", options: ["Diámetro, agrupación y taper", "Solo el color del empaque", "La longitud de la ceja", "La fase inflamatoria"], answer: 0, explanation: "La huella y el comportamiento dependen de la combinación completa de puntas, calibre, disposición y afilado." },
];

export const cases = [
  { title: "Inicio demasiado compacto", situation: "El inicio se ve tan intenso como la cola y la ceja pierde ligereza.", diagnosis: "Falta de gradiente y exceso de saturación en la zona de luz.", action: "Reducir la densidad de impactos en el inicio y construir una transición progresiva hacia cuerpo y cola." },
  { title: "Piel fina con eritema temprano", situation: "La piel acepta color con facilidad, pero enrojece antes de completar varias pasadas.", diagnosis: "Tejido delicado con riesgo de sobretrabajo.", action: "Mantener una mano ligera, reducir repeticiones y evaluar la respuesta antes de buscar más intensidad." },
  { title: "Color irregular al cicatrizar", situation: "El resultado presenta zonas más densas y otras con baja retención.", diagnosis: "Distribución inconsistente, posiblemente asociada a cambios de velocidad, presión o distancia.", action: "Evaluar el patrón completo en el retoque y corregir solo las zonas necesarias con parámetros estables." },
  { title: "Confusión entre stroke y profundidad", situation: "Una profesional cree que un stroke de 3 mm significa penetrar 3 mm en piel.", diagnosis: "Interpretación incorrecta del parámetro mecánico.", action: "Recordar que el stroke es el recorrido del sistema; la profundidad real depende del control manual y del tejido." },
];
